name = "RdWaveFiles"
uuid = "46bd9b67-29e2-46b0-bb29-da07b42f7d11"
authors = ["Naoki Maeda <fnkyksj@gmail.com> and contributors"]
version = "0.2.0-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
